apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  annotations:
    getambassador.io/rolloutId: 2edf1369-2f64-48fb-ac36-96b5801edca3
  creationTimestamp: null
  name: rollout-demo
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rollout-demo
  strategy:
    canary:
      canaryService: rollout-demo-canary
      stableService: rollout-demo
      steps:
      - setWeight: 10
      - pause:
          duration: 30
      - setWeight: 20
      - pause:
          duration: 30
      - setWeight: 30
      - pause:
          duration: 30
      - setWeight: 40
      - pause:
          duration: 30
      - setWeight: 50
      - pause:
          duration: 30
      - setWeight: 60
      - pause:
          duration: 30
      - setWeight: 70
      - pause:
          duration: 30
      - setWeight: 80
      - pause:
          duration: 30
      - setWeight: 90
      - pause:
          duration: 30
      - setWeight: 100
      - pause:
          duration: 30
      trafficRouting:
        ambassador:
          mappings:
          - rollout-demo-mapping
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rollout-demo
    spec:
      containers:
      - args:
        - -text=VERSION 1
        - -listen=:8080
        image: hashicorp/http-echo:0.1.1
        imagePullPolicy: Always
        name: echo-v1
        ports:
        - containerPort: 8080
        resources: {}
status:
  blueGreen: {}
  canary: {}
